// Demo Data for Charwa Trading
// Used when Supabase is not configured

const DEMO_TRUCKS = [
    {
        id: '1',
        slug: 'daf-xf-530-2021-abc123',
        status: 'active',
        title_de: 'DAF XF 530 FT Super Space Cab',
        title_en: 'DAF XF 530 FT Super Space Cab',
        title_tr: 'DAF XF 530 FT Super Space Cab',
        description_de: 'Sehr gepflegter DAF XF 530 mit Super Space Cab. Vollständige Servicehistorie, alle Inspektionen bei DAF durchgeführt. Fahrzeug ist sofort verfügbar.\n\nAusstattung:\n- Automatikgetriebe\n- Standklimaanlage\n- Kühlschrank\n- Navigationssystem\n- Lederlenkrad',
        description_en: 'Well-maintained DAF XF 530 with Super Space Cab. Complete service history, all inspections performed at DAF. Vehicle is immediately available.\n\nEquipment:\n- Automatic transmission\n- Parking air conditioning\n- Refrigerator\n- Navigation system\n- Leather steering wheel',
        description_tr: 'Bakımlı DAF XF 530 Super Space Cab. Tam servis geçmişi, tüm bakımlar DAF\'ta yapılmış. Araç hemen teslim edilebilir.',
        price: 89500,
        price_type: 'negotiable',
        vat_status: 'margin',
        brand: 'DAF',
        model: 'XF 530',
        year: 2021,
        mileage: 420000,
        condition: 'used',
        engine_power: 530,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'Super Space Cab',
        axle_config: '4x2',
        fuel_tank_capacity: 1300,
        features: ['retarder', 'ac', 'standheater', 'navigation', 'cruise_control', 'refrigerator', 'leather'],
        images: [
            'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80',
            'https://images.unsplash.com/photo-1586191582056-fbbb89899395?w=800&q=80',
            'https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=800&q=80'
        ],
        video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        location_city: 'Berlin',
        location_country: 'Germany',
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
        view_count: 245,
        featured: true
    },
    {
        id: '2',
        slug: 'man-tgx-18-510-2020-def456',
        status: 'active',
        title_de: 'MAN TGX 18.510 XXL Cab',
        title_en: 'MAN TGX 18.510 XXL Cab',
        title_tr: 'MAN TGX 18.510 XXL Kabin',
        description_de: 'MAN TGX 18.510 mit XXL Fahrerhaus. Erstbesitz, lückenlose Servicehistorie. Ideal für den Fernverkehr.',
        description_en: 'MAN TGX 18.510 with XXL cab. First owner, complete service history. Ideal for long-haul transport.',
        description_tr: 'MAN TGX 18.510 XXL kabin. İlk sahibinden, tam servis geçmişi.',
        price: 78000,
        price_type: 'fixed',
        vat_status: 'margin',
        brand: 'MAN',
        model: 'TGX 18.510',
        year: 2020,
        mileage: 385000,
        condition: 'used',
        engine_power: 510,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'XXL Cab',
        axle_config: '4x2',
        fuel_tank_capacity: 1200,
        features: ['retarder', 'ac', 'standheater', 'navigation', 'cruise_control', 'abs', 'esp'],
        images: [
            'https://images.unsplash.com/photo-1586191582056-fbbb89899395?w=800&q=80',
            'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80'
        ],
        video_url: null,
        location_city: 'Hamburg',
        location_country: 'Germany',
        created_at: '2024-01-10T14:30:00Z',
        updated_at: '2024-01-10T14:30:00Z',
        view_count: 189,
        featured: false
    },
    {
        id: '3',
        slug: 'volvo-fh-500-2022-ghi789',
        status: 'active',
        title_de: 'VOLVO FH 500 Globetrotter XL',
        title_en: 'VOLVO FH 500 Globetrotter XL',
        title_tr: 'VOLVO FH 500 Globetrotter XL',
        description_de: 'Neuwertiger Volvo FH 500 mit Globetrotter XL Kabine. Nur 180.000 km, wie neu.',
        description_en: 'Like-new Volvo FH 500 with Globetrotter XL cab. Only 180,000 km, excellent condition.',
        description_tr: 'Sıfır gibi Volvo FH 500 Globetrotter XL kabin. Sadece 180.000 km.',
        price: 125000,
        price_type: 'fixed',
        vat_status: 'excluded',
        brand: 'VOLVO',
        model: 'FH 500',
        year: 2022,
        mileage: 180000,
        condition: 'used',
        engine_power: 500,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'Globetrotter XL',
        axle_config: '4x2',
        fuel_tank_capacity: 1400,
        features: ['retarder', 'ac', 'standheater', 'navigation', 'cruise_control', 'abs', 'esp', 'parking_sensors', 'refrigerator', 'tv', 'leather', 'bed'],
        images: [
            'https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=800&q=80',
            'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80',
            'https://images.unsplash.com/photo-1586191582056-fbbb89899395?w=800&q=80'
        ],
        video_url: null,
        location_city: 'Munich',
        location_country: 'Germany',
        created_at: '2024-01-20T09:00:00Z',
        updated_at: '2024-01-20T09:00:00Z',
        view_count: 312,
        featured: true
    },
    {
        id: '4',
        slug: 'scania-r450-2019-jkl012',
        status: 'active',
        title_de: 'SCANIA R 450 Highline',
        title_en: 'SCANIA R 450 Highline',
        title_tr: 'SCANIA R 450 Highline',
        description_de: 'Zuverlässiger Scania R 450 mit Highline Kabine. Guter Allgemeinzustand.',
        description_en: 'Reliable Scania R 450 with Highline cab. Good overall condition.',
        description_tr: 'Güvenilir Scania R 450 Highline kabin. İyi genel durum.',
        price: 62000,
        price_type: 'negotiable',
        vat_status: 'margin',
        brand: 'SCANIA',
        model: 'R 450',
        year: 2019,
        mileage: 520000,
        condition: 'used',
        engine_power: 450,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'Highline',
        axle_config: '4x2',
        fuel_tank_capacity: 1100,
        features: ['retarder', 'ac', 'cruise_control', 'abs', 'esp'],
        images: [
            'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80'
        ],
        video_url: null,
        location_city: 'Frankfurt',
        location_country: 'Germany',
        created_at: '2024-01-05T16:00:00Z',
        updated_at: '2024-01-05T16:00:00Z',
        view_count: 156,
        featured: false
    },
    {
        id: '5',
        slug: 'mercedes-actros-1845-2021-mno345',
        status: 'reserved',
        title_de: 'MERCEDES-BENZ Actros 1845 StreamSpace',
        title_en: 'MERCEDES-BENZ Actros 1845 StreamSpace',
        title_tr: 'MERCEDES-BENZ Actros 1845 StreamSpace',
        description_de: 'Mercedes Actros 1845 mit StreamSpace Kabine. Reserviert für Kunde aus der Türkei.',
        description_en: 'Mercedes Actros 1845 with StreamSpace cab. Reserved for customer from Turkey.',
        description_tr: 'Mercedes Actros 1845 StreamSpace kabin. Türkiye\'den müşteri için rezerve.',
        price: 95000,
        price_type: 'fixed',
        vat_status: 'margin',
        brand: 'MERCEDES-BENZ',
        model: 'Actros 1845',
        year: 2021,
        mileage: 290000,
        condition: 'used',
        engine_power: 450,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'StreamSpace',
        axle_config: '4x2',
        fuel_tank_capacity: 1250,
        features: ['retarder', 'ac', 'standheater', 'navigation', 'cruise_control', 'abs', 'esp', 'parking_sensors'],
        images: [
            'https://images.unsplash.com/photo-1586191582056-fbbb89899395?w=800&q=80',
            'https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=800&q=80'
        ],
        video_url: null,
        location_city: 'Cologne',
        location_country: 'Germany',
        created_at: '2024-01-12T11:00:00Z',
        updated_at: '2024-01-18T14:00:00Z',
        view_count: 278,
        featured: false
    },
    {
        id: '6',
        slug: 'daf-xf-480-2020-pqr678',
        status: 'sold',
        title_de: 'DAF XF 480 Space Cab',
        title_en: 'DAF XF 480 Space Cab',
        title_tr: 'DAF XF 480 Space Cab',
        description_de: 'VERKAUFT - DAF XF 480 Space Cab, exportiert nach Turkmenistan.',
        description_en: 'SOLD - DAF XF 480 Space Cab, exported to Turkmenistan.',
        description_tr: 'SATILDI - DAF XF 480 Space Cab, Türkmenistan\'a ihraç edildi.',
        price: 72000,
        price_type: 'fixed',
        vat_status: 'margin',
        brand: 'DAF',
        model: 'XF 480',
        year: 2020,
        mileage: 410000,
        condition: 'used',
        engine_power: 480,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'Space Cab',
        axle_config: '4x2',
        fuel_tank_capacity: 1300,
        features: ['retarder', 'ac', 'cruise_control'],
        images: [
            'https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=800&q=80'
        ],
        video_url: null,
        location_city: 'Berlin',
        location_country: 'Germany',
        created_at: '2023-12-01T10:00:00Z',
        updated_at: '2024-01-08T09:00:00Z',
        view_count: 423,
        featured: false
    },
    {
        id: '7',
        slug: 'man-tgx-18-470-2019-stu901',
        status: 'active',
        title_de: 'MAN TGX 18.470 XLX Cab',
        title_en: 'MAN TGX 18.470 XLX Cab',
        title_tr: 'MAN TGX 18.470 XLX Kabin',
        description_de: 'Solider MAN TGX mit XLX Kabine. Ideal für Osteuropa-Export.',
        description_en: 'Solid MAN TGX with XLX cab. Ideal for Eastern Europe export.',
        description_tr: 'Sağlam MAN TGX XLX kabin. Doğu Avrupa ihracatı için ideal.',
        price: 58000,
        price_type: 'negotiable',
        vat_status: 'margin',
        brand: 'MAN',
        model: 'TGX 18.470',
        year: 2019,
        mileage: 480000,
        condition: 'used',
        engine_power: 470,
        emission_class: 'euro6',
        transmission: 'manual',
        cab_type: 'XLX Cab',
        axle_config: '4x2',
        fuel_tank_capacity: 1150,
        features: ['ac', 'cruise_control', 'abs'],
        images: [
            'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80',
            'https://images.unsplash.com/photo-1586191582056-fbbb89899395?w=800&q=80'
        ],
        video_url: null,
        location_city: 'Düsseldorf',
        location_country: 'Germany',
        created_at: '2024-01-08T13:00:00Z',
        updated_at: '2024-01-08T13:00:00Z',
        view_count: 134,
        featured: false
    },
    {
        id: '8',
        slug: 'volvo-fh-460-2018-vwx234',
        status: 'draft',
        title_de: 'VOLVO FH 460 Globetrotter',
        title_en: 'VOLVO FH 460 Globetrotter',
        title_tr: 'VOLVO FH 460 Globetrotter',
        description_de: '[ENTWURF] Volvo FH 460 - Fotos folgen',
        description_en: '[DRAFT] Volvo FH 460 - Photos coming soon',
        description_tr: '[TASLAK] Volvo FH 460 - Fotoğraflar yakında',
        price: 52000,
        price_type: 'fixed',
        vat_status: 'margin',
        brand: 'VOLVO',
        model: 'FH 460',
        year: 2018,
        mileage: 580000,
        condition: 'used',
        engine_power: 460,
        emission_class: 'euro6',
        transmission: 'automatic',
        cab_type: 'Globetrotter',
        axle_config: '4x2',
        fuel_tank_capacity: 1200,
        features: ['retarder', 'ac'],
        images: [],
        video_url: null,
        location_city: 'Stuttgart',
        location_country: 'Germany',
        created_at: '2024-01-22T08:00:00Z',
        updated_at: '2024-01-22T08:00:00Z',
        view_count: 0,
        featured: false
    }
];

// Demo mode flag
const DEMO_MODE = CONFIG.SUPABASE_URL.includes('YOUR_PROJECT');

if (DEMO_MODE) {
    console.log('%c🚛 DEMO MODE ACTIVE', 'background: #22c55e; color: #0a0a0a; padding: 4px 8px; border-radius: 4px; font-weight: bold;');
    console.log('Using mock data. Configure Supabase in js/config.js for real data.');
}
